

[env]
TERM = "xterm-256color"


[window]

opacity = 0.8


[font]

normal = { family = "Hurmit Nerd Font" }

bold = { family = "Hurmit Nerd Font" }

italic = { family = "Hurmit Nerd Font" }

bold_italic = { family = "Hurmit Nerd Font" }

size = 10


[mouse]

hide_when_typing = true

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"	
]
